# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2127f1349dcf8214a144dcd2cf2b401497f1ca59400f804530a2278a185d2e82592aab312293deb6968141292178598228da8cf9c9318baad5454794faadf8db

test:
  secret_key_base: 83a044f2a605f8e5183724edb8ce348b93c6623a7d677607ec98ac158df1f0987ebd35ad96c8641acb17e91706d388356aff9c2b4112f29b66e5d85ed021f446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>



development:
  secret_key_base: 7bfb8c82d35b56a28a847d5a033991cb67c694ca4193aaf8e62cd5151051add92f8060ec2daad96581235ef76891135cfc388387c12590c81aa2394d637a0530

test:
  secret_key_base: 33a375370b6e70ec611cc521bd8531e85f400be9d0364399afb26173846c3bf2ca40b25ed291d99a2a6ce2bd85aa6cdc7f7607d7e87393cec929a587a0e9fcc5

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

